### ISSUE TITLE
Blog post link dead

### ISSUE THREAD

**Issue by SeynalKim** [simonguest/android-btxfr#7]
I wanted to use this library but I can't dig into more details on how can I send specific type of data. I understand that this library was created a while ago, But maybe the author @simonguest can update the `blog post` link for more details.

**Comment by simonguest** [comment]
Hi @SeynalKim - I've moved my blog since, but the post was almost identical to the readme on the GH repo. I'll go ahead and update the readme to remove the confusing reference to the old blog article. Feel free to raise another issue if you have issues with the library.
